##Metadata for 'saltmarsh.bird.data' list object##

# nsites: The number of surveyed sites (1,792)
# nsurveys: The number of replicate surveys conducted annually at a site (2)
# nwindows: The number of 1-minute time windows/bins per survey (5)
# nyears: The number of years of survey data collected (9). Some years had very little
#         data collection and thus were dropped from analysis. The retained years were:
#         2011, 2012, 2013, 2014, 2015, 2016, 2018, 2021, and 2022
# max.n: The maximum number of individuals of a given species observed on a survey
# y: A 4-D array containing the count data from surveys
# noise: A 3-D array containing categorical data describing the magnitude of background
#        noise on a survey.
# UVVR: A dataframe containing the mean unvegetated to vegetated ratio value at each 
#       site. The mean value was generated by averaging annual values generated for 
#       each year from 2014 - 2018. The trend column contains the estimated slope of a
#       line fitted to the 2014 - 2018 data, indicating the annual rate of change in
#       UVVR value at a given site.
# nobservers: The number of unique observers that conducted point count surveys (231)
# sunrise: The number of seconds after local sunrise when a survey was conducted. 
#          Negative values indicate that the survey was conducted prior to sunrise.
# latitudes: The latitudes of the survey points
# patch.index: An indexer indicating the marsh patch that each survey point was 
#              located within (1 - 529).
# npatches: The number of marsh patches surveyed (529)
# tides: The rate of local sea-level rise (mm / year) at each point, extracted from
#        NOAA tide gauge data.
# patch.area: The area of each marsh patch (ha)
# patch.road.dens: The length of roads (m) contained within a 500 m buffer surrounding
#                 a marsh patch, divided by the area of the marsh patch + 500 m buffer.
# observer: An indexer indicating the identity of the observer that conducted 
#           each survey (1 - 231).
# veg.props: The proportional cover of each of 8 vegetation cover types within the
#            50 m radius survey point area. Cover type options are: high marsh, 
#            pool / panne, low marsh, mudflat, Phragmites australis,
#            upland terrestrial border, upland, or open water.
# sky: A 3-D array containing categorical data describing the weather conditions 
#      of a survey.
# temp: A 3-D array of the temperature (F) on a survey.
# j.day: A 3-D array of the julian date (number of days since Jan. 1) of a survey.
# y.time: a 5-D array indicating the time window (0 - 5) of each observed individual
#         detected on a survey. Data are collapsed down to the first detection of a 
#         species, rather than the first detection of each individual, when 
#         fitting models.
# max.tide: The highest recorded tide (in m above MHW) observed by the closest NOAA
#           tide gauge to each survey point in each year (April - September).
# nspecies: The number of focal saltmarsh bird species (5)
# year.index: An indexer for estimating the annual population trend (needed as the
#             trend is estimated over a 12 year period, but only 9 years of data are
#             used in models).
# restrictions: A dataframe indicating whether or not each site is tidally restricted,
#               and if it is, what is the magnitude of restriction.
# state: A dataframe containing binary indicator variables for each survey point,
#        indicating which state the survey point is located in.
# state.index: A vector indicating which state each survey point is in, with values
#        from 1 - 10 representing each state sampled from Maine to Virginia.